server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # --- CONFIGURACIÓN CORS (CRUCIAL PARA EL FRONTEND) ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" # Puerto por defecto de Vite
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

      # --- RUTAS A MICROSERVICIOS ---
      routes:
        # M7: Seguridad
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # M1: Inventario
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/tools/**

        # M2: Préstamos
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**

        # M3: Clientes
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/clients/**

        # M4: Tarifas
        - id: tariff-service
          uri: lb://tariff-service
          predicates:
            - Path=/api/tariffs/**

        # M5: Kardex
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**

        # M6: Reportes
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true